AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-fastapi-mangum
  SAM template testing FastAPI + mangum

Globals:
  Function:
    Timeout: 3

Resources:
  AppHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/main/
      Handler: main.lambda_handler
      Runtime: python3.8
      Events:
        AllPaths:
          Type: HttpApi
      Tracing: Active
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: sam-fastapi-mangum

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AppHandlerFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt AppHandlerFunction.Arn
  AppHandlerFunctionIamRole:
    Description: "Lambda Function IAM Role ARN"
    Value: !GetAtt AppHandlerFunction.Arn